version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-107-22-83-3.compute-1.amazonaws.com
            port: '5432'
            database: d22nv2m19mfi59
            schema: schema.graphql
            user: onxsbbrjrnddww
            password: d37e4e2e642859b7bfb318566671797a244a519c1da5777bb50d95ed291e8c43
            migrations: true